# Generated by Django 4.1.3 on 2022-12-29 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, default='media/images/profpics/defaultprofpic.jpg', null=True, upload_to='media/images/profpics/'),
        ),
    ]
