# Generated by Django 4.1.3 on 2022-12-20 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_date_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='date_created',
            new_name='date_joined',
        ),
    ]
