# Generated by Django 4.1.3 on 2022-11-23 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weet',
            name='privacy',
            field=models.CharField(default='public', max_length=9),
            preserve_default=False,
        ),
    ]
