# Generated by Django 4.1.3 on 2023-01-09 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weets', '0002_rename_parent_weet_child'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dig',
            name='comment',
        ),
        migrations.AddField(
            model_name='weet',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='childrenWeets', to='weets.weet'),
        ),
        migrations.AlterField(
            model_name='weet',
            name='child',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parentWeet', to='weets.weet'),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
