# Generated by Django 4.1.3 on 2022-11-24 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weets', '0002_weet_privacy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weet',
            name='privacy',
            field=models.CharField(choices=[('public', 'public'), ('followers', 'followers'), ('private', 'private')], default='public', max_length=9),
        ),
    ]
