# Generated by Django 4.1.3 on 2022-11-25 18:25

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('weets', '0003_alter_weet_privacy'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Digs',
            new_name='Dig',
        ),
    ]
