# Generated by Django 4.1.4 on 2023-01-17 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weets', '0003_remove_dig_comment_weet_parent_alter_weet_child_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weet',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
