# Generated by Django 4.1.3 on 2022-11-25 18:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('weets', '0004_rename_digs_dig'),
    ]

    operations = [
        migrations.AddField(
            model_name='weet',
            name='digs',
            field=models.ManyToManyField(blank=True, null=True, related_name='weet_user', through='weets.Dig', to=settings.AUTH_USER_MODEL),
        ),
    ]
