# Generated by Django 4.1.3 on 2022-11-25 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weets', '0006_alter_comment_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dig',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='weets.comment'),
        ),
        migrations.AlterField(
            model_name='dig',
            name='weet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='weets.weet'),
        ),
    ]
