# Generated by Django 4.1.3 on 2022-12-20 19:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('weets', '0007_alter_dig_comment_alter_dig_weet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weet',
            name='digs',
            field=models.ManyToManyField(related_name='weet_user', through='weets.Dig', to=settings.AUTH_USER_MODEL),
        ),
    ]
